import type { Metadata } from "next";

import { Inter as FontSans } from "next/font/google";
import { cn } from "@/shared/lib/css";

import "./globals.css";
import "@xyflow/react/dist/style.css";

const fontSans = FontSans({
  subsets: ["latin", "cyrillic-ext"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased dark flex flex-col",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
